### ISSUE TITLE
Test artifact of workflow-step-api included as a dependency

### ISSUE THREAD

**Issue by ibauersachs** [jenkinsci/office-365-connector-plugin#161]
The change in #146 to update workflow-step-api probably causes our Jenkins to fail to start with exceptions as below.

https://github.com/jenkinsci/office-365-connector-plugin/blob/1cd9685db18a2956edc1c56d49bbf291deb25257/pom.xml#L103

Only setting the classifier to `tests` includes the artifact in the production build, which is likely not what was intended with this change.

```
2019-07-28 19:49:00.746+0000 [id=28]	WARNING	hudson.model.Descriptor#load: Failed to load /var/lib/jenkins/<some-plugin-config>.xml
java.lang.NullPointerException
	at org.jvnet.hudson.test.TestExtensionLoader.isActive(TestExtensionLoader.java:96)
	at org.jvnet.hudson.test.TestExtensionLoader.findExtensions(TestExtensionLoader.java:61)
	at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:347)
	at hudson.ExtensionList.load(ExtensionList.java:381)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:317)
	at hudson.ExtensionList.iterator(ExtensionList.java:172)
	at jenkins.security.ClassFilterImpl.isBlacklisted(ClassFilterImpl.java:303)
	at hudson.remoting.ClassFilter$1.isBlacklisted(ClassFilter.java:125)
	at hudson.util.XStream2$BlacklistedTypesConverter.canConvert(XStream2.java:563)
	at com.thoughtworks.xstream.core.DefaultConverterLookup.lookupConverterForType(DefaultConverterLookup.java:59)
	at com.thoughtworks.xstream.XStream$1.lookupConverterForType(XStream.java:498)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:56)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1189)
	at hudson.util.XStream2.unmarshal(XStream2.java:161)
	at hudson.util.XStream2.unmarshal(XStream2.java:132)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1173)
	at hudson.XmlFile.unmarshal(XmlFile.java:178)
```

**Comment by damianszczepanik** [comment]
Could be. Do you know how to test it?

**Comment by ibauersachs** [comment]
Install the plugin on Jenkins 2.187 and see Jenkins crash as soon as the plugin is installed.

**Comment by damianszczepanik** [comment]
I have this version installed and no problem so far. I guess there is some interference with other plugin that causes the problem. Can you find which one? Does the exception help with this investigation?

**Comment by ibauersachs** [comment]
Did you have Blue Ocean installed? That's afaik were the workflow-step-api originates. But no, I cannot isolate it any further. It already took me hours to find that this plugin here was ultimately responsible for the above exception.
And no, the exceptions don't help. Jenkins fails to load the configuration of _any_ plugin (and its own config.xml).

Anyway, having a `tests` artifact on the regular classpath is just wrong.

**Comment by damianszczepanik** [comment]
Tested with blue ocean without success.

Will you be able to test with patch if I prepare unofficial release before we agree that it helps?

**Comment by ibauersachs** [comment]
Yes

**Comment by damianszczepanik** [comment]
Do you have https://plugins.jenkins.io/workflow-step-api and if so - what version?

**Comment by ibauersachs** [comment]
org.jenkins-ci.plugins.workflow:workflow-step-api:2.20

**Comment by damianszczepanik** [comment]
So I have same configuration that works. Can you share Jenkins output as if there was a problem with the plugin I expect there must be some exception provided in Jenkins log file

**Comment by ibauersachs** [comment]
The log is just full of the exceptions quoted when I first opened the issue. For every. single. installed. plugin.
I've opened a PR - a single line change. Tests run successfully, Jenkins starts successfully and notifications arrive in Teams.
