### ISSUE TITLE
Unable to post webhook

### ISSUE THREAD

**Issue by felixPG** [jenkinsci/office-365-connector-plugin#214]
Hi all:

After config the connector in Teams and in a jenkins test job the plugin does not work in my environment. 

```[Office365connector] Failed to post data to webhook ```
```
javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
	at sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:450)
	at org.apache.commons.httpclient.protocol.SSLProtocolSocketFactory.verifyHostName(SSLProtocolSocketFactory.java:257)
	at org.apache.commons.httpclient.protocol.SSLProtocolSocketFactory.createSocket(SSLProtocolSocketFactory.java:167)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:714)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:394)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:178)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:404)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:330)
	at jenkins.plugins.office365connector.HttpWorker.run(HttpWorker.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
Im try with the oncoming webhook conector and with the Office 365 jenkins connector and both fails with the same error.

I think that is a certificate verification problem. Please, any workaround to bypass a certification check when using this plugin please?

Regards

Felix

**Comment by damianszczepanik** [comment]
Honestly, I have no idea

**Comment by lamcw** [comment]
I think it could be related to your firewall rules. Check your firewall to allow your Jenkins server to access your webhook endpoints.

**Comment by felixPG** [comment]
Thanks all!, problem solved adding a corporate firewall rule! But please, any workaround to bypass certificate check?
