### ISSUE TITLE
Plugin not using proxy

### ISSUE THREAD

**Issue by dsargent3220** [jenkinsci/office-365-connector-plugin#220]
I don't understand what is broken here.  I've looked at the code in the HttpWorker.java file in the plugin and it looks to me like the plugin should be using the configured proxy but ours is not.
I've tested t with the our security department and they are 1. Not seeing any hits on the proxy from the node the build is running on and 2. Seeing a deny in our firewall from the node to the office URL.

Here's our config
* Jenkins 2.222.4 running in Kubernetes
* Plugin office-365-connector-plugin version 4.13.0
* AFAIK all the places one would configure the proxy have been, i.e. in the Helm chart answers for Jenkins as:
```yaml
  initContainerEnv:
    - name: HTTP_PROXY
      value: "http://10.100.1.171:8080"
    - name: HTTPS_PROXY
      value: "http://10.100.1.171:8080"
    - name: NO_PROXY
      value: "localhost,localaddress,svc.cluster.local,default.svc,ad.selinc.com,10.43.0.1,127.0.0.1,127.0.0.0,0.0.0.0,127.0.0.0/8,10.0.0.0/8,10.*.*.*,10.*,172.16.0.0/12,192.168.0.0/16"
    - name: http_proxy
      value: "http://10.100.1.171:8080"
    - name: https_proxy
      value: "http://10.100.1.171:8080"
    - name: no_proxy
      value: "localhost,localaddress,svc.cluster.local,default.svc,ad.selinc.com,10.43.0.1,127.0.0.1,127.0.0.0,0.0.0.0,127.0.0.0/8,10.0.0.0/8,10.*.*.*,10.*,172.16.0.0/12,192.168.0.0/16"
  containerEnv:
    - name: HTTP_PROXY
      value: "http://10.100.1.171:8080"
    - name: HTTPS_PROXY
      value: "http://10.100.1.171:8080"
    - name: NO_PROXY
      value: "localhost,localaddress,svc.cluster.local,default.svc,ad.selinc.com,10.43.0.1,127.0.0.1,127.0.0.0,0.0.0.0,127.0.0.0/8,10.0.0.0/8,10.*.*.*,10.*,172.16.0.0/12,192.168.0.0/16"
    - name: http_proxy
      value: "http://10.100.1.171:8080"
    - name: https_proxy
      value: "http://10.100.1.171:8080"
    - name: no_proxy
      value: "localhost,localaddress,svc.cluster.local,default.svc,ad.selinc.com,10.43.0.1,127.0.0.1,127.0.0.0,0.0.0.0,127.0.0.0/8,10.0.0.0/8,10.*.*.*,10.*,172.16.0.0/12,192.168.0.0/16"
    - name: CASC_JENKINS_CONFIG
      value: "/var/jenkins_home/casc_configs/"
  javaOpts: >-
    -Dhttp.proxyHost=10.100.1.171
    -Dhttp.proxyPort=8080
    -Dhttps.proxyHost=10.100.1.171
    -Dhttps.proxyPort=8080
    -Dhttp.nonProxyHosts="localhost|localaddress|*svc.cluster.local*|*default.svc*|*kubernetes*|*.ad.selinc.com|127.0.0.1|127.0.0.0|0.0.0.0|10.43.0.1|127.0.0.0/8|127.*.*.*|10.0.0.0/8|10.*.*.*|10.*|172.16.0.0/12|192.168.0.0/16|192.168.*.*"
```
Here is the error we are seeing in the logs
```[Office365connector] Failed to post data to webhook - https://outlook.office.com/webhook/<redacted>
org.apache.commons.httpclient.ConnectTimeoutException: The host did not accept the connection within timeout of 30000 ms
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:162)
	at org.apache.commons.httpclient.protocol.SSLProtocolSocketFactory.createSocket(SSLProtocolSocketFactory.java:161)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:714)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:394)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:178)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:404)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:330)
	at jenkins.plugins.office365connector.HttpWorker.run(HttpWorker.java:83)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:285)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:147)
	... 12 more
```
We also set the proxies in our JNLP container def, not that it should matter for this.
Our proxy does not require authentication.

Am I missing something?

**Comment by dsargent3220** [comment]
Oops, the plugin section has its own proxies.  
Found it and fixed it.
