### ISSUE TITLE
Jenkins FreeStyle Job Encountering java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by robblis** [jenkinsci/office-365-connector-plugin#345]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Jenkins: 2.440.3
OS: Windows Server 2016 - 10.0
Java: 11.0.22 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
---
JDK_Parameter_Plugin:1.2
Office-365-Connector:4.13.2
ace-editor:1.1
acunetix:1.2.14
ant:1.13
antisamy-markup-formatter:162.v0e6ec0fcfcf6
apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
asm-api:9.7-33.v4d23ef79fcc8
authentication-tokens:1.53.v1c90fd9191a_b_
aws-java-sdk-minimal:1.12.287-357.vf82d85a_6eefd
blueocean:1.27.12
blueocean-autofavorite:1.2.4
blueocean-bitbucket-pipeline:1.27.12
blueocean-commons:1.27.12
blueocean-config:1.27.12
blueocean-core-js:1.27.12
blueocean-dashboard:1.27.12
blueocean-display-url:2.4.2
blueocean-events:1.27.12
blueocean-git-pipeline:1.27.12
blueocean-github-pipeline:1.27.12
blueocean-i18n:1.27.12
blueocean-jira:1.25.2
blueocean-jwt:1.27.12
blueocean-personalization:1.27.12
blueocean-pipeline-api-impl:1.27.12
blueocean-pipeline-editor:1.27.12
blueocean-pipeline-scm-api:1.27.12
blueocean-rest:1.27.12
blueocean-rest-impl:1.27.12
blueocean-web:1.27.12
bootstrap4-api:4.6.0-6
bootstrap5-api:5.3.3-1
bouncycastle-api:2.30.1.77-225.v26ea_c9455fd9
branch-api:2.1152.v6f101e97dd77
build-timeout:1.20
build-timestamp:1.0.3
caffeine-api:3.1.8-133.v17b_1ff2e0599
calendar-view:0.3.1
change-assembly-version-plugin:1.10
checks-api:2.2.0
cloudbees-bitbucket-branch-source:883.v041fa_695e9c2
cloudbees-folder:6.901.vb_4c7a_da_75da_3
command-launcher:1.6
commons-httpclient3-api:3.1-3
commons-lang3-api:3.13.0-62.v7d18e55f51e2
commons-text-api:1.11.0-95.v22a_d30ee5d36
config-file-provider:973.vb_a_80ecb_9a_4d0
copyartifact:1.46.3
credentials:1337.v60b_d7b_c7b_c9f
credentials-binding:677.vdc9d38cb_254d
display-url-api:2.200.vb_9327d658781
docker-commons:439.va_3cb_0a_6a_fb_29
docker-java-api:3.1.5.2
docker-plugin:1.2.6
docker-workflow:1.26
durable-task:555.v6802fe0f0b_82
echarts-api:5.5.0-1
electricflow:1.1.34
email-ext:1806.v856a_01a_fa_39a_
envinject:2.908.v66a_774b_31d93
envinject-api:1.199.v3ce31253ed13
external-monitor-job:215.v2e88e894db_f8
favorite:2.208.v91d65b_7792a_c
file-operations:1.11
filesystem-list-parameter-plugin:0.0.11
font-awesome-api:6.5.1-3
git:5.2.1
git-client:4.7.0
git-server:114.v068a_c7cc2574
github:1.38.0
github-api:1.318-461.v7a_c09c9fa_d63
github-branch-source:1787.v8b_8cd49a_f8f1
gradle:1.37.1
gson-api:2.10.1-15.v0d99f670e0a_7
handlebars:1.1.1
handy-uri-templates-2-api:2.1.8-30.v7e777411b_148
htmlpublisher:1.33
installshield:1.0.3
instance-identity:185.v303dc7c645f9
ionicons-api:70.v2959a_b_74e3cf
jackson2-api:2.17.0-379.v02de8ec9f64c
jakarta-activation-api:2.1.3-1
jakarta-mail-api:2.1.3-1
javadoc:217.v905b_86277a_2a_
javax-activation-api:1.2.0-6
javax-mail-api:1.6.2-5
jaxb:2.3.9-1
jdk-tool:1.3
jenkins-design-language:1.27.12
jersey2-api:2.42-147.va_28a_44603b_d5
jira:3.13
jjwt-api:0.11.5-112.ve82dfb_224b_a_d
joda-time-api:2.12.7-29.v5a_b_e3a_82269a_
jquery:1.12.4-1
jquery-detached:1.2.1
jquery3-api:3.7.1-2
jsch:0.1.55.2
json-api:20240303-41.v94e11e6de726
json-path-api:2.9.0-58.v62e3e85b_a_655
junit:1265.v65b_14fa_f12f0
kubernetes:4208.v4017b_a_27a_d67
kubernetes-client-api:6.10.0-240.v57880ce8b_0b_2
kubernetes-credentials:0.11
ldap:725.v3cb_b_711b_1a_ef
lockable-resources:2.12
mailer:472.vf7c289a_4b_420
mapdb-api:1.0.9-40.v58107308b_7a_7
matrix-auth:3.0
matrix-project:822.824.v14451b_c0fd42
maven-plugin:3.16
mercurial:1260.vdfb_723cdcc81
metrics:4.2.21-449.v6960d7c54c69
mina-sshd-api-common:2.12.0-90.v9f7fb_9fa_3d3b_
mina-sshd-api-core:2.12.0-90.v9f7fb_9fa_3d3b_
momentjs:1.1.1
msbuild:1.30
mstest:1.0.5
mstestrunner:1.3.0
nodejs:1.6.1
nuget:1.1
okhttp-api:4.11.0-172.vda_da_1feeb_c6e
pam-auth:1.4.1
performance:3.17
pipeline-build-step:540.vb_e8849e1a_b_d8
pipeline-github-lib:1.0
pipeline-graph-analysis:216.vfd8b_ece330ca_
pipeline-groovy-lib:704.vc58b_8890a_384
pipeline-input-step:495.ve9c153f6067b_
pipeline-milestone-step:119.vdfdc43fc3b_9a_
pipeline-model-api:2.2198.v41dd8ef6dd56
pipeline-model-declarative-agent:1.1.1
pipeline-model-definition:2.2198.v41dd8ef6dd56
pipeline-model-extensions:2.2198.v41dd8ef6dd56
pipeline-npm:0.9.2
pipeline-rest-api:2.34
pipeline-stage-step:312.v8cd10304c27a_
pipeline-stage-tags-metadata:2.2198.v41dd8ef6dd56
pipeline-stage-view:2.34
pipeline-utility-steps:2.16.2
plain-credentials:179.vc5cb_98f6db_38
plugin-usage-plugin:3.0
plugin-util-api:4.1.0
popper-api:1.16.1-2
popper2-api:2.11.6-1
powershell:1.4
protecode-sc:0.18.2
pubsub-light:1.18
python:1.3
python-wrapper:1.0.3
resource-disposer:0.13
s3:0.12.1
scm-api:689.v237b_6d3a_ef7f
script-security:1335.vf07d9ce377a_e
snakeyaml-api:2.2-111.vc6598e30cc65
snyk-security-scanner:3.2.6
sse-gateway:1.26
ssh-credentials:337.v395d2403ccd4
ssh-slaves:1.31.2
sshd:3.322.v159e91f6a_550
structs:337.v1b_04ea_4df7c8
subversion:1256.vee91953217b_6
summary_report:1.15
text-file-operations:1.3.2
tfs:5.157.0
thinBackup:1.10
timestamper:1.26
token-macro:400.v35420b_922dcb_
trilead-api:2.142.v748523a_76693
variant:60.v7290fc0eb_b_cd
veracode-scan:21.9.16.0
vstestrunner:1.0.8
vsts-cd:1.3
windows-slaves:1.8.1
workflow-aggregator:2.6
workflow-api:1291.v51fd2a_625da_7
workflow-basic-steps:1058.vcb_fc1e3a_21a_9
workflow-cps:3894.vd0f0248b_a_fc4
workflow-cps-global-lib:612.v55f2f80781ef
workflow-durable-task-step:1336.v768003e07199
workflow-job:1400.v7fd111b_ec82f
workflow-multibranch:773.vc4fe1378f1d5
workflow-scm-step:427.v4ca_6512e7df1
workflow-step-api:657.v03b_e8115821b_
workflow-support:896.v175a_a_9c5b_78f
ws-cleanup:0.37

  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Controller: Windows Server 2016 Standard (Java 11.0)
Agent: Windows Server 2019 Standard (Java 11.0)

### Reproduction steps

1. Create FreeStyle Jenkins Job
2. Add WebHook to Office 365 Connector (Set all alerts)
3. Run Job

### Expected Results

Successful Job

### Actual Results

Job threw exception...

FATAL: org/apache/commons/httpclient/methods/RequestEntity
java.lang.ClassNotFoundException: org.apache.commons.httpclient.methods.RequestEntity
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at jenkins.util.URLClassLoader2.findClass(URLClassLoader2.java:35)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:594)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
Caused: java.lang.NoClassDefFoundError: org/apache/commons/httpclient/methods/RequestEntity
	at jenkins.plugins.office365connector.Office365ConnectorWebhookNotifier.executeWorker(Office365ConnectorWebhookNotifier.java:115)
	at jenkins.plugins.office365connector.Office365ConnectorWebhookNotifier.sendBuildStartedNotification(Office365ConnectorWebhookNotifier.java:66)
	at jenkins.plugins.office365connector.WebhookJobProperty.prebuild(WebhookJobProperty.java:44)
	at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:869)
	at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:864)
	at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:860)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:523)
	at hudson.model.Run.execute(Run.java:1895)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:442)
[Office365connector] Matched status 'FAILURE' for webhook with name 'PG&E QAext'.

### Anything else?

I removed the WebHook from the Office 365 connector and the Job succeeded.

**Comment by damianszczepanik** [comment]
First try to upgrade Jenkins and plugin - I'm testing plugin against recent LTS version of Jenkins

**Comment by robblis** [comment]
Upgrading the plugin fixed the issue. Thanks for the guidance.
